"""Add French medical education fields

Revision ID: 208a10ce8b3b
Revises: 8b8d73305acb
Create Date: 2025-08-25 18:17:15.115275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208a10ce8b3b'
down_revision = '8b8d73305acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer_image', sa.String(), nullable=True))
    op.alter_column('device_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('device_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device_sessions', 'device_fingerprint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_device_sessions_fingerprint', table_name='device_sessions')
    op.drop_index('idx_device_sessions_user_id', table_name='device_sessions')
    op.create_index(op.f('ix_device_sessions_device_fingerprint'), 'device_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_device_sessions_id'), 'device_sessions', ['id'], unique=False)
    op.add_column('questions', sa.Column('study_year', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('module', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('unite', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('cours', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('exam_type', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('question_image', sa.String(), nullable=True))
    op.drop_index('ix_questions_chapter', table_name='questions')
    op.drop_index('ix_questions_course', table_name='questions')
    op.create_index(op.f('ix_questions_cours'), 'questions', ['cours'], unique=False)
    op.create_index(op.f('ix_questions_exam_type'), 'questions', ['exam_type'], unique=False)
    op.create_index(op.f('ix_questions_module'), 'questions', ['module'], unique=False)
    op.create_index(op.f('ix_questions_study_year'), 'questions', ['study_year'], unique=False)
    op.create_index(op.f('ix_questions_unite'), 'questions', ['unite'], unique=False)
    op.drop_column('questions', 'chapter')
    op.drop_column('questions', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('course', sa.VARCHAR(), nullable=True))
    op.add_column('questions', sa.Column('chapter', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_questions_unite'), table_name='questions')
    op.drop_index(op.f('ix_questions_study_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_module'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_cours'), table_name='questions')
    op.create_index('ix_questions_course', 'questions', ['course'], unique=False)
    op.create_index('ix_questions_chapter', 'questions', ['chapter'], unique=False)
    op.drop_column('questions', 'question_image')
    op.drop_column('questions', 'exam_type')
    op.drop_column('questions', 'cours')
    op.drop_column('questions', 'unite')
    op.drop_column('questions', 'module')
    op.drop_column('questions', 'study_year')
    op.drop_index(op.f('ix_device_sessions_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_device_fingerprint'), table_name='device_sessions')
    op.create_index('idx_device_sessions_user_id', 'device_sessions', ['user_id'], unique=False)
    op.create_index('idx_device_sessions_fingerprint', 'device_sessions', ['device_fingerprint'], unique=False)
    op.alter_column('device_sessions', 'device_fingerprint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('device_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('answers', 'answer_image')
    # ### end Alembic commands ### 