"""Add student fields, question fields, answer labels, and activation keys

Revision ID: 8b8d73305acb
Revises: 0001
Create Date: 2025-08-17 16:48:31.806722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8d73305acb'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_keys_id'), 'activation_keys', ['id'], unique=False)
    op.create_index(op.f('ix_activation_keys_key'), 'activation_keys', ['key'], unique=True)
    op.add_column('answers', sa.Column('option_label', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_answers_option_label'), 'answers', ['option_label'], unique=False)
    op.add_column('questions', sa.Column('speciality', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('chapter', sa.String(), nullable=True))
    op.create_index(op.f('ix_questions_chapter'), 'questions', ['chapter'], unique=False)
    op.create_index(op.f('ix_questions_speciality'), 'questions', ['speciality'], unique=False)
    op.add_column('users', sa.Column('year_of_study', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('speciality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'speciality')
    op.drop_column('users', 'year_of_study')
    op.drop_index(op.f('ix_questions_speciality'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter'), table_name='questions')
    op.drop_column('questions', 'chapter')
    op.drop_column('questions', 'speciality')
    op.drop_index(op.f('ix_answers_option_label'), table_name='answers')
    op.drop_column('answers', 'option_label')
    op.drop_index(op.f('ix_activation_keys_key'), table_name='activation_keys')
    op.drop_index(op.f('ix_activation_keys_id'), table_name='activation_keys')
    op.drop_table('activation_keys')
    # ### end Alembic commands ### 